### ISSUE TITLE
Runtime crash with multi Application module project.

### ISSUE THREAD

**Issue by AmniX** [MiSikora/laboratory#131]
Hi @MiSikora 
Hope you are doing well.

I've encountered a Runtime crash in Laboratory where we have two application modules in same project.

How to Reproduce?

1. You must have more than one application modules in same codebase.
2. All modules must use laboratory gradle plugin (io.mehow.laboratory)
3. Use feature flags on all modules.
4. Run any of the application module and try opening Laboratory. 
There will be a runtime crash follows by ClassNotFoundException

For me, Crashlog looks like below.

> `java.lang.ClassNotFoundException: com.module.two.laboratory.sdk.Feature1
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.module.one.laboratory.sdk.GeneratedFeatureFactory.create(GeneratedFeatureFactory.kt:15)
        at io.mehow.laboratory.inspector.InspectorViewModel$$special$$inlined$mapValues$lambda$1$1.invokeSuspend(InspectorViewModel.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`
        
What we have figured out so far is the **laboratory** is expecting all the feature flags in both of the modules.

i.e. If module **one** have 2 features and Module **two** have another 2 features.
Then Laboratory is expecting 4 features in total so far, No matter what the module is being compiled. 
Since it's being accessed with Reflection `Class.forName` so module compiles fine but crashes as soon you open Laboratory.

Laboratory Version: 0.12.1
Android Version: Any

Let me know if you need anything else. 

Cheers :)

**Comment by MiSikora** [comment]
Hey @AmniX,

This is unfortunately expected and is described in the last section of [multi–module support](https://mehow.io/laboratory/gradle-plugin/#multi-module-support).

> Gradle plugin discovers all feature flags and their sources that are a part of the same project. There might be some rare cases when you’d like to exclude some modules from contributing its feature flags to the `featureFactory()` or `sourcedStorage()`. This can be achieved with project filtering.

```groovy
apply plugin: "io.mehow.laboratory"

laboratory {
  featureFactory {
    projectFilter { project -> project.name != "module-a" }
  }

  sourcedStorage {
    projectFilter { project -> project.name != "module-a" }
  }
}
```

> This way, `:module-a` will not contribute its feature flags to the generation of a feature factory and feature storage.

The reason for using reflection is because it's better in terms of composability. If flags are generated as `internal` or are transitive but as `implementation` then they wouldn't be visible in the generated code as classes won't be accessible.

As the issue affects only QA part of the library I don't see it as something extremely bad. Rather as an annoyance. Anyway I hope this clarifies things. I probably could make the warning more explicit in the documentation.

**Comment by AmniX** [comment]
Thanks for Clarification @MiSikora :)
