### ISSUE TITLE
Can't generate feature flags with Kotlin 1.7.20

### ISSUE THREAD

**Issue by vudzkostek** [MiSikora/laboratory#284]
After upgrading kotlin in project to version 1.7.20, when trying to assemble module with feature flags, we get:
```
Cause 1: java.lang.IllegalArgumentException: Did not find Kotlin source set
        at io.mehow.laboratory.gradle.SourceSetContributionKt.contributeToKotlin(SourceSetContribution.kt:61)
        at io.mehow.laboratory.gradle.SourceSetContributionKt.contributeToSourceSets(SourceSetContribution.kt:23)
        at io.mehow.laboratory.gradle.LaboratoryPlugin.addSourceSets(LaboratoryPlugin.kt:154)
        at io.mehow.laboratory.gradle.LaboratoryPlugin.registerFeaturesTask$lambda-11(LaboratoryPlugin.kt:74)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
```
Module does not have kotlin/java code, only build.gradle with feature flags declaration:
```groovy
apply plugin: 'kotlin'
apply plugin: 'io.mehow.laboratory'

laboratory {
    packageName = "eu.some.package"

    featureFactory {
        packageName = "eu.some.package"
        isPublic = true
    }

    feature("SomeFlag") {
        description = "Some description"

        withDefaultOption("Disabled")
        withOption("Enabled")

        withDefaultSource("Remote")
    }
}
```

**Comment by MiSikora** [comment]
Thanks for the report. Looks like the same issue [as this one](https://github.com/square/wire/pull/2310). I can work on it probably sometime next week unless you feel like making a PR.

**Comment by vudzkostek** [comment]
This should probably be reopened as after "fix" generated code is no longer being compiled

**Comment by MiSikora** [comment]
Oh ok, I'll take into this a look some time soon.
